# Generated by Django 4.1.1 on 2022-09-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferenceroom',
            old_name='capacity',
            new_name='room_capacity',
        ),
    ]
