# Generated by Django 4.1.1 on 2022-09-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_rename_capacity_conferenceroom_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceroom',
            name='projector',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='room_capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
