# Generated by Django 4.1.1 on 2022-09-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_alter_conferenceroom_projector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('comment', models.TextField(null='no comment added')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.conferenceroom')),
            ],
        ),
    ]
