# Generated by Django 4.1.1 on 2022-09-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_roomreservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomreservation',
            name='date',
        ),
    ]
