# Generated by Django 4.1.1 on 2022-09-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_alter_roomreservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservation',
            old_name='date',
            new_name='reservation_date',
        ),
    ]
